version: "3.9"
services:
  test_db1:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --general-log=1 --general-log-file=/var/log/mysql/general-log.log
    networks:
      - test-network
    env_file:
      - test.env
    volumes:
      - "./logs/test_db1:/var/log/mysql:rw"
  test_db2:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --general-log=1 --general-log-file=/var/log/mysql/general-log.log
    networks:
      - test-network
    env_file:
      - test.env
    volumes:
      - "./logs/test_db2:/var/log/mysql:rw"
  app:
    build: .
    command: sh -c 'pytest -x'
    volumes:
      - "./:/app/:rw"
      - "~/Documents/mindsdb/dfsql/dfsql:/usr/local/lib/python3.8/site-packages/dfsql"
    links:
      - test_db1
      - test_db2
    depends_on:
      - test_db1
      - test_db2
    env_file:
      - test.env
    networks:
      - test-network

networks:
  test-network:
