name: run unit tests

on:
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.7,3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install --no-cache-dir -e .[test]
        pip install coveralls pytest-cov
    - name: Run unit tests
      run: pytest --cov=geks tests/ --cov-report xml 
    - name: Coveralls
      uses: coverallsapp/github-action@v2.2.2
      with:
        github-token: ${{ secrets.github_token }}
        file: ./coverage.xml
        flag-name: run-${{ join(matrix.*, '-') }}
        git-branch: main
        parallel: true
        
  coveralls-finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v2.2.2
        with:
          github-token: ${{ secrets.G_TOKEN }}
          parallel-finished: true
